### PR TITLE
Document how to use matrix_upload

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Review by poljar — APPROVED** [review]

**Comment by bwkam** [comment]
I still can't understand how to upload files

**Comment by jspricke** [comment]
@bwkam Can you open an issue and paste what you tried?

**Comment by bwkam** [comment]
I'm just not sure what the file argument is. Is it a path on my local FS? I'll open an issue, but I thought it wasn't that important.

**Comment by jspricke** [comment]
Yes, it is a file on the local FS.

**Comment by bwkam** [comment]
Well, I get this when I try uploading.
`Error with command 'Error with command 'matrix_upload'` 
It's not installed under PATH perhaps that's why.

**Comment by jspricke** [comment]
Yes, as documented in https://github.com/poljar/weechat-matrix?tab=readme-ov-file#uploading-files

**Comment by bwkam** [comment]
Can I debug this further? I'm not very sure if it's a PATH issue
For reference, I'm using `weechat-matrix` from nixpkgs, which seems to [expose `matrix_upload` properly](https://github.com/NixOS/nixpkgs/blob/6143fc5eeb9c4f00163267708e26191d1e918932/pkgs/applications/networking/irc/weechat/scripts/weechat-matrix/default.nix#L75C1-L75C55)

**Comment by jspricke** [comment]
I think this is better discussed in a new issue with the nix package.

**Comment by bwkam** [comment]
Fair, thanks for the help!

**Pull request merged**
